require:
  - standard
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*
    - config/**/*
    - db/schema.rb
  TargetRubyVersion: 2.7.4

RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
Bundler/DuplicatedGem:
  Enabled: false